### ISSUE TITLE
Database tables size

### ISSUE THREAD

**Issue by jgphpc** [Fahey-McLay/xalt#19]
## xalt/0.7.6
On [Daint](http://www.cscs.ch/computers/piz_daint), 1 month of production data approximately takes:

```
Table: xalt_object      = 624 M / 1.2 millions rows
Table: xalt_total_env   = 10 G  / 1.2 millions rows
Table: join_run_env     = 14 G  / 45 millions rows
```

In order to setup our mysql server, we would like to know if that is expected behaviour or if that is more than it should be. Any feedback from other sites would be greatly appreciated too :grinning:

**Comment by rtmclay** [comment]
Storing the environment with each job takes up a great deal of room.    In 0.7.6, you can reduce the size of the environment by filtering out more environment variables.  If you go to xalt_run_submission.py at line 333, you'll see an array ignoreKeyA = [ ... ]. 

You can add more variables to ignore there.   The devel version (1.6+) has a more sophisticated way of handling the ignore list.

There are two reasons that I can think of store environment variables.  One is provide the environment for reproducability and for debugging.    The second reason to save them is to be able to do SQL tests to see what programs ran with a certain env. var. set.   At our site, we have rarely needed the environment variables to do an SQL test.  

There are variables like the number of threads that are in xalt_run that we do use.  

It would be nice to keep them all but it may not be necessary.

**Comment by jgphpc** [comment]
Thanks a lot for your reply. We (with @victorusu) decided to go with a whitelist instead because on the Cray the number of variables to ignore can be large. It seems to work ok.

* libexec/xalt_run_submission.py

```python
   983     for k in os.environ:
   984       v = os.environ[k]
   985       keep = False
   986       # looking for key in list to be kept
   987       for pat in tobeKeptKeyA:
   988         m = pat.search(k)
   989         # found the key
   990         if (m):
   991           keep = True
   992           break
   993       m = shFuncPat.search(v)
   994       if (m):
   995         keep = True
   996       if (keep):
   997         envT[k] = v
   998     return envT
```
