### ISSUE TITLE
GPU tracking fails to build due to “ in xalt_initialize.c line 510

### ISSUE THREAD

**Issue by mknoxnv** [Fahey-McLay/xalt#39]
With GPU tracking enabled xalt fails to build.  The issue is the “  in this section of xalt_initialize.c, should be ".

Original:
DEBUG0(stderr, “   -> May need to enable accounting mode: sudo nvidia-smi -am 1\n”);

Fixed:
DEBUG0(stderr, "   -> May need to enable accounting mode: sudo nvidia-smi -am 1\n");

**Comment by rtmclay** [comment]
Thanks for reporting this error. HEAD has been fixed.
